version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: "yourpassword"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - oracle-data:/opt/oracle/oradata

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@oracle-db:1521/ORCLCDB"
      SPRING_DATASOURCE_USERNAME: "yourusername"
      SPRING_DATASOURCE_PASSWORD: "yourpassword"

volumes:
  oracle-data:
